version: 0.2

phases:
  install:
    commands:
      - "yum install unzip -y"
      - "wget https://releases.hashicorp.com/terraform/0.13.1/terraform_0.13.1_linux_amd64.zip"
      - "unzip terraform_0.13.1_linux_amd64.zip"
      - "mv terraform /usr/local/bin/"

  pre_build:
    commands:
      - terraform init

  build:
    commands:
      - terraform $TF_COMMAND -auto-approve

  post_build:
    commands:
      - echo terraform $TF_COMMAND completed on `date`
